baseURL = 'http://www.guitarrehab.pt/'
languageCode = 'en-us'
title = 'Guitar Rehab'
defaultContentLanguage = 'pt-pt'

[params]
slogan = 'Reabilitate your guitar and mind'

[languages]
[languages.pt-pt]
name="pt"
contentDir = 'content/pt'
weight = 1

[languages.en]
name="en"
contentDir = 'content/en'
weight = 2

[module]
[module.hugoVersion]
min = "0.92.0"

[[module.imports]]
path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
